// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: api/grpc/agent/v1/agent.proto

package pkg

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Запрос стрима, инкапсулирующий сообщения от агента к серверу (Upstream)
type ConnectStreamRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ConnectStreamRequest_Telemetry
	//	*ConnectStreamRequest_TerminalOutput
	Payload       isConnectStreamRequest_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectStreamRequest) Reset() {
	*x = ConnectStreamRequest{}
	mi := &file_api_grpc_agent_v1_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectStreamRequest) ProtoMessage() {}

func (x *ConnectStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_agent_v1_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectStreamRequest.ProtoReflect.Descriptor instead.
func (*ConnectStreamRequest) Descriptor() ([]byte, []int) {
	return file_api_grpc_agent_v1_agent_proto_rawDescGZIP(), []int{0}
}

func (x *ConnectStreamRequest) GetPayload() isConnectStreamRequest_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ConnectStreamRequest) GetTelemetry() *TelemetryPayload {
	if x != nil {
		if x, ok := x.Payload.(*ConnectStreamRequest_Telemetry); ok {
			return x.Telemetry
		}
	}
	return nil
}

func (x *ConnectStreamRequest) GetTerminalOutput() *TerminalOutput {
	if x != nil {
		if x, ok := x.Payload.(*ConnectStreamRequest_TerminalOutput); ok {
			return x.TerminalOutput
		}
	}
	return nil
}

type isConnectStreamRequest_Payload interface {
	isConnectStreamRequest_Payload()
}

type ConnectStreamRequest_Telemetry struct {
	Telemetry *TelemetryPayload `protobuf:"bytes,1,opt,name=telemetry,proto3,oneof"`
}

type ConnectStreamRequest_TerminalOutput struct {
	TerminalOutput *TerminalOutput `protobuf:"bytes,2,opt,name=terminal_output,json=terminalOutput,proto3,oneof"`
}

func (*ConnectStreamRequest_Telemetry) isConnectStreamRequest_Payload() {}

func (*ConnectStreamRequest_TerminalOutput) isConnectStreamRequest_Payload() {}

// Заглушка структуры телеметрии (в будущем будет расширена под батчинг)
type TelemetryPayload struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CpuUsagePercent float64                `protobuf:"fixed64,1,opt,name=cpu_usage_percent,json=cpuUsagePercent,proto3" json:"cpu_usage_percent,omitempty"`
	RamUsageMb      float64                `protobuf:"fixed64,2,opt,name=ram_usage_mb,json=ramUsageMb,proto3" json:"ram_usage_mb,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TelemetryPayload) Reset() {
	*x = TelemetryPayload{}
	mi := &file_api_grpc_agent_v1_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TelemetryPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelemetryPayload) ProtoMessage() {}

func (x *TelemetryPayload) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_agent_v1_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelemetryPayload.ProtoReflect.Descriptor instead.
func (*TelemetryPayload) Descriptor() ([]byte, []int) {
	return file_api_grpc_agent_v1_agent_proto_rawDescGZIP(), []int{1}
}

func (x *TelemetryPayload) GetCpuUsagePercent() float64 {
	if x != nil {
		return x.CpuUsagePercent
	}
	return 0
}

func (x *TelemetryPayload) GetRamUsageMb() float64 {
	if x != nil {
		return x.RamUsageMb
	}
	return 0
}

// Вывод из системного терминала (stdout/stderr)
type TerminalOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TerminalOutput) Reset() {
	*x = TerminalOutput{}
	mi := &file_api_grpc_agent_v1_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TerminalOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TerminalOutput) ProtoMessage() {}

func (x *TerminalOutput) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_agent_v1_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TerminalOutput.ProtoReflect.Descriptor instead.
func (*TerminalOutput) Descriptor() ([]byte, []int) {
	return file_api_grpc_agent_v1_agent_proto_rawDescGZIP(), []int{2}
}

func (x *TerminalOutput) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// Ответ стрима, инкапсулирующий команды от сервера к агенту (Downstream)
type ConnectStreamResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ConnectStreamResponse_TerminalInput
	//	*ConnectStreamResponse_ExecuteScript
	Payload       isConnectStreamResponse_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectStreamResponse) Reset() {
	*x = ConnectStreamResponse{}
	mi := &file_api_grpc_agent_v1_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectStreamResponse) ProtoMessage() {}

func (x *ConnectStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_agent_v1_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectStreamResponse.ProtoReflect.Descriptor instead.
func (*ConnectStreamResponse) Descriptor() ([]byte, []int) {
	return file_api_grpc_agent_v1_agent_proto_rawDescGZIP(), []int{3}
}

func (x *ConnectStreamResponse) GetPayload() isConnectStreamResponse_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ConnectStreamResponse) GetTerminalInput() *TerminalInput {
	if x != nil {
		if x, ok := x.Payload.(*ConnectStreamResponse_TerminalInput); ok {
			return x.TerminalInput
		}
	}
	return nil
}

func (x *ConnectStreamResponse) GetExecuteScript() *ExecuteScript {
	if x != nil {
		if x, ok := x.Payload.(*ConnectStreamResponse_ExecuteScript); ok {
			return x.ExecuteScript
		}
	}
	return nil
}

type isConnectStreamResponse_Payload interface {
	isConnectStreamResponse_Payload()
}

type ConnectStreamResponse_TerminalInput struct {
	TerminalInput *TerminalInput `protobuf:"bytes,1,opt,name=terminal_input,json=terminalInput,proto3,oneof"`
}

type ConnectStreamResponse_ExecuteScript struct {
	ExecuteScript *ExecuteScript `protobuf:"bytes,2,opt,name=execute_script,json=executeScript,proto3,oneof"`
}

func (*ConnectStreamResponse_TerminalInput) isConnectStreamResponse_Payload() {}

func (*ConnectStreamResponse_ExecuteScript) isConnectStreamResponse_Payload() {}

// Ввод команд в терминал агента (stdin)
type TerminalInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TerminalInput) Reset() {
	*x = TerminalInput{}
	mi := &file_api_grpc_agent_v1_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TerminalInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TerminalInput) ProtoMessage() {}

func (x *TerminalInput) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_agent_v1_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TerminalInput.ProtoReflect.Descriptor instead.
func (*TerminalInput) Descriptor() ([]byte, []int) {
	return file_api_grpc_agent_v1_agent_proto_rawDescGZIP(), []int{4}
}

func (x *TerminalInput) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// Команда на запуск bash/powershell скрипта
type ExecuteScript struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ScriptContent  string                 `protobuf:"bytes,1,opt,name=script_content,json=scriptContent,proto3" json:"script_content,omitempty"`
	TimeoutSeconds int64                  `protobuf:"varint,2,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ExecuteScript) Reset() {
	*x = ExecuteScript{}
	mi := &file_api_grpc_agent_v1_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteScript) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteScript) ProtoMessage() {}

func (x *ExecuteScript) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_agent_v1_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteScript.ProtoReflect.Descriptor instead.
func (*ExecuteScript) Descriptor() ([]byte, []int) {
	return file_api_grpc_agent_v1_agent_proto_rawDescGZIP(), []int{5}
}

func (x *ExecuteScript) GetScriptContent() string {
	if x != nil {
		return x.ScriptContent
	}
	return ""
}

func (x *ExecuteScript) GetTimeoutSeconds() int64 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

var File_api_grpc_agent_v1_agent_proto protoreflect.FileDescriptor

const file_api_grpc_agent_v1_agent_proto_rawDesc = "" +
	"\n" +
	"\x1dapi/grpc/agent/v1/agent.proto\x12\x11api.grpc.agent.v1\"\xb4\x01\n" +
	"\x14ConnectStreamRequest\x12C\n" +
	"\ttelemetry\x18\x01 \x01(\v2#.api.grpc.agent.v1.TelemetryPayloadH\x00R\ttelemetry\x12L\n" +
	"\x0fterminal_output\x18\x02 \x01(\v2!.api.grpc.agent.v1.TerminalOutputH\x00R\x0eterminalOutputB\t\n" +
	"\apayload\"`\n" +
	"\x10TelemetryPayload\x12*\n" +
	"\x11cpu_usage_percent\x18\x01 \x01(\x01R\x0fcpuUsagePercent\x12 \n" +
	"\fram_usage_mb\x18\x02 \x01(\x01R\n" +
	"ramUsageMb\"$\n" +
	"\x0eTerminalOutput\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"\xb8\x01\n" +
	"\x15ConnectStreamResponse\x12I\n" +
	"\x0eterminal_input\x18\x01 \x01(\v2 .api.grpc.agent.v1.TerminalInputH\x00R\rterminalInput\x12I\n" +
	"\x0eexecute_script\x18\x02 \x01(\v2 .api.grpc.agent.v1.ExecuteScriptH\x00R\rexecuteScriptB\t\n" +
	"\apayload\"#\n" +
	"\rTerminalInput\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"_\n" +
	"\rExecuteScript\x12%\n" +
	"\x0escript_content\x18\x01 \x01(\tR\rscriptContent\x12'\n" +
	"\x0ftimeout_seconds\x18\x02 \x01(\x03R\x0etimeoutSeconds2v\n" +
	"\fAgentService\x12f\n" +
	"\rConnectStream\x12'.api.grpc.agent.v1.ConnectStreamRequest\x1a(.api.grpc.agent.v1.ConnectStreamResponse(\x010\x01B\x06Z\x04pkg/b\x06proto3"

var (
	file_api_grpc_agent_v1_agent_proto_rawDescOnce sync.Once
	file_api_grpc_agent_v1_agent_proto_rawDescData []byte
)

func file_api_grpc_agent_v1_agent_proto_rawDescGZIP() []byte {
	file_api_grpc_agent_v1_agent_proto_rawDescOnce.Do(func() {
		file_api_grpc_agent_v1_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_grpc_agent_v1_agent_proto_rawDesc), len(file_api_grpc_agent_v1_agent_proto_rawDesc)))
	})
	return file_api_grpc_agent_v1_agent_proto_rawDescData
}

var file_api_grpc_agent_v1_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_api_grpc_agent_v1_agent_proto_goTypes = []any{
	(*ConnectStreamRequest)(nil),  // 0: api.grpc.agent.v1.ConnectStreamRequest
	(*TelemetryPayload)(nil),      // 1: api.grpc.agent.v1.TelemetryPayload
	(*TerminalOutput)(nil),        // 2: api.grpc.agent.v1.TerminalOutput
	(*ConnectStreamResponse)(nil), // 3: api.grpc.agent.v1.ConnectStreamResponse
	(*TerminalInput)(nil),         // 4: api.grpc.agent.v1.TerminalInput
	(*ExecuteScript)(nil),         // 5: api.grpc.agent.v1.ExecuteScript
}
var file_api_grpc_agent_v1_agent_proto_depIdxs = []int32{
	1, // 0: api.grpc.agent.v1.ConnectStreamRequest.telemetry:type_name -> api.grpc.agent.v1.TelemetryPayload
	2, // 1: api.grpc.agent.v1.ConnectStreamRequest.terminal_output:type_name -> api.grpc.agent.v1.TerminalOutput
	4, // 2: api.grpc.agent.v1.ConnectStreamResponse.terminal_input:type_name -> api.grpc.agent.v1.TerminalInput
	5, // 3: api.grpc.agent.v1.ConnectStreamResponse.execute_script:type_name -> api.grpc.agent.v1.ExecuteScript
	0, // 4: api.grpc.agent.v1.AgentService.ConnectStream:input_type -> api.grpc.agent.v1.ConnectStreamRequest
	3, // 5: api.grpc.agent.v1.AgentService.ConnectStream:output_type -> api.grpc.agent.v1.ConnectStreamResponse
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_api_grpc_agent_v1_agent_proto_init() }
func file_api_grpc_agent_v1_agent_proto_init() {
	if File_api_grpc_agent_v1_agent_proto != nil {
		return
	}
	file_api_grpc_agent_v1_agent_proto_msgTypes[0].OneofWrappers = []any{
		(*ConnectStreamRequest_Telemetry)(nil),
		(*ConnectStreamRequest_TerminalOutput)(nil),
	}
	file_api_grpc_agent_v1_agent_proto_msgTypes[3].OneofWrappers = []any{
		(*ConnectStreamResponse_TerminalInput)(nil),
		(*ConnectStreamResponse_ExecuteScript)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_grpc_agent_v1_agent_proto_rawDesc), len(file_api_grpc_agent_v1_agent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_grpc_agent_v1_agent_proto_goTypes,
		DependencyIndexes: file_api_grpc_agent_v1_agent_proto_depIdxs,
		MessageInfos:      file_api_grpc_agent_v1_agent_proto_msgTypes,
	}.Build()
	File_api_grpc_agent_v1_agent_proto = out.File
	file_api_grpc_agent_v1_agent_proto_goTypes = nil
	file_api_grpc_agent_v1_agent_proto_depIdxs = nil
}
